/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --types
Author: VertaScan (https://sketchfab.com/VertaScan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bumble-bee-hover-craft-21234354d78f4a53a5786e1f5a5e764b
Title: Bumble Bee Hover Craft
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Torus_poche_0: THREE.Mesh
    Torus_RUBBER_0: THREE.Mesh
    Torus_INTERIOR_0: THREE.Mesh
    Torus_NAV_PANEL_0: THREE.Mesh
    Torus_VENT_0: THREE.Mesh
    Torus_rear_light_0: THREE.Mesh
    Torus_STEEL_0: THREE.Mesh
    Torus_steel_trim_0: THREE.Mesh
    Torus_GLASS_0: THREE.Mesh
    Torus_engine_0: THREE.Mesh
    Torus_front_lights_0: THREE.Mesh
    Plane_STEEL_0: THREE.Mesh
    Plane001_INTERIOR_0: THREE.Mesh
    space_pilot_pilot_0: THREE.Mesh
    space_pilot_pilot_0_1: THREE.Mesh
    space_pilot_pilot_0_2: THREE.Mesh
    space_pilot_pilot_0_3: THREE.Mesh
    space_pilot_pilot_0_4: THREE.Mesh
    space_pilot_pilot_0_5: THREE.Mesh
    space_pilot_pilot_0_6: THREE.Mesh
    space_pilot_pilot_0_7: THREE.Mesh
    space_pilot_pilot_0_8: THREE.Mesh
    space_pilot_pilot_0_9: THREE.Mesh
    space_pilot_pilot2_0: THREE.Mesh
    Cube013_INTERIOR_0: THREE.Mesh
    Circle_seat_0: THREE.Mesh
    Circle_NAV_PANEL_0: THREE.Mesh
    Elbow_Joint002_tire_0: THREE.Mesh
    Sphere002_STEEL_0: THREE.Mesh
    Sphere002_front_lights_0: THREE.Mesh
  }
  materials: {
    poche: THREE.MeshPhysicalMaterial
    RUBBER: THREE.MeshStandardMaterial
    INTERIOR: THREE.MeshStandardMaterial
    NAV_PANEL: THREE.MeshStandardMaterial
    VENT: THREE.MeshStandardMaterial
    rear_light: THREE.MeshStandardMaterial
    STEEL: THREE.MeshStandardMaterial
    steel_trim: THREE.MeshStandardMaterial
    GLASS: THREE.MeshStandardMaterial
    engine: THREE.MeshStandardMaterial
    front_lights: THREE.MeshStandardMaterial
    pilot: THREE.MeshStandardMaterial
    pilot2: THREE.MeshStandardMaterial
    seat: THREE.MeshStandardMaterial
    tire: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 252.31, -11.7]} rotation={[-1.39, Math.PI / 2, 0]} scale={[112.31, 112.31, 303.23]}>
          <mesh geometry={nodes.Torus_poche_0.geometry} material={materials.poche} />
          <mesh geometry={nodes.Torus_RUBBER_0.geometry} material={materials.RUBBER} />
          <mesh geometry={nodes.Torus_INTERIOR_0.geometry} material={materials.INTERIOR} />
          <mesh geometry={nodes.Torus_NAV_PANEL_0.geometry} material={materials.NAV_PANEL} />
          <mesh geometry={nodes.Torus_VENT_0.geometry} material={materials.VENT} />
          <mesh geometry={nodes.Torus_rear_light_0.geometry} material={materials.rear_light} />
          <mesh geometry={nodes.Torus_STEEL_0.geometry} material={materials.STEEL} />
          <mesh geometry={nodes.Torus_steel_trim_0.geometry} material={materials.steel_trim} />
          <mesh geometry={nodes.Torus_GLASS_0.geometry} material={materials.GLASS} />
          <mesh geometry={nodes.Torus_engine_0.geometry} material={materials.engine} />
          <mesh geometry={nodes.Torus_front_lights_0.geometry} material={materials.front_lights} />
        </group>
        <group position={[10.46, 234.03, -68.72]} rotation={[0.18, 0, 0]} scale={49.45}>
          <mesh geometry={nodes.space_pilot_pilot_0.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_1.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_2.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_3.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_4.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_5.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_6.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_7.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_8.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_9.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot2_0.geometry} material={materials.pilot2} />
          <mesh geometry={nodes.Plane_STEEL_0.geometry} material={materials.STEEL} position={[-0.21, -1.67, -0.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.62, 0.56, 2.02]} />
          <mesh geometry={nodes.Plane001_INTERIOR_0.geometry} material={materials.INTERIOR} position={[-0.21, -1.67, -0.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.62, 0.56, 2.02]} />
        </group>
        <group position={[0.48, 226.43, -3]} rotation={[-1.9, 0, 0]} scale={38.92}>
          <mesh geometry={nodes.Circle_seat_0.geometry} material={materials.seat} />
          <mesh geometry={nodes.Circle_NAV_PANEL_0.geometry} material={materials.NAV_PANEL} />
        </group>
        <group position={[0, 440.25, 43.62]} rotation={[0.18, 0, 0]} scale={7.52}>
          <mesh geometry={nodes.Sphere002_STEEL_0.geometry} material={materials.STEEL} />
          <mesh geometry={nodes.Sphere002_front_lights_0.geometry} material={materials.front_lights} />
        </group>
        <mesh geometry={nodes.Cube013_INTERIOR_0.geometry} material={materials.INTERIOR} position={[0.51, 192.3, 7.77]} rotation={[-1.39, 0, 0]} scale={18.9} />
        <mesh geometry={nodes.Elbow_Joint002_tire_0.geometry} material={materials.tire} position={[0.31, 166.71, 4.53]} rotation={[1.75, 0, -Math.PI / 2]} scale={5.07} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
