/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.glb
Author: VertaScan (https://sketchfab.com/VertaScan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hover-car-model-6d9244926d4f4d81a4ad77f60d396926
Title: Hover Car Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 74.1, -49]} rotation={[-Math.PI / 2, 0, 0]} scale={[90.77, 285.08, 89.03]}>
          <mesh geometry={nodes.hover_2001_base_mesh_mat_0.geometry} material={materials.base_mesh_mat} />
          <mesh geometry={nodes.hover_2001_metal_trim_0.geometry} material={materials.metal_trim} />
          <mesh geometry={nodes.hover_2001_vents_1_0.geometry} material={materials.vents_1} />
          <mesh geometry={nodes.hover_2001_seat_0.geometry} material={materials.seat} />
          <mesh geometry={nodes.hover_2001_VENTS_0.geometry} material={materials.VENTS} />
          <mesh geometry={nodes.hover_2001_panel_0.geometry} material={materials.panel} />
          <mesh geometry={nodes.hover_2001_glass_1_0.geometry} material={materials.glass_1} />
        </group>
        <group position={[0, 54.99, -103.65]} scale={21.14}>
          <mesh geometry={nodes.space_pilot_pilot_0.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_1.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_2.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_3.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_4.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_5.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_6.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_7.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_8.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot_0_9.geometry} material={materials.pilot} />
          <mesh geometry={nodes.space_pilot_pilot2_0.geometry} material={materials.pilot2} />
        </group>
        <group position={[77.88, 39.36, 170.74]} rotation={[-Math.PI / 2, 0, 0.38]} scale={10.94}>
          <mesh geometry={nodes.Cube006_base_mesh_mat_0.geometry} material={materials.base_mesh_mat} />
          <mesh geometry={nodes.Cube006_beam_0.geometry} material={materials.beam} />
          <mesh geometry={nodes.Cube006_tire_0.geometry} material={materials.tire} />
        </group>
        <mesh geometry={nodes.hover_2008_base_mesh_mat_0.geometry} material={materials.base_mesh_mat} position={[-56.15, 147.96, -14.73]} rotation={[-Math.PI / 2, 0, 0]} scale={[90.77, 285.08, 89.03]} />
        <mesh geometry={nodes.hover_2015_base_mesh_mat_0.geometry} material={materials.base_mesh_mat} position={[55.48, 147.51, -14.06]} rotation={[-Math.PI / 2, 0, 0]} scale={[90.77, 285.08, 89.03]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
