/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --types
Author: Carrozze DÄULARI (https://sketchfab.com/alhertenberger)
License: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
Source: https://sketchfab.com/3d-models/corvette-c2-nero-9456ab58673a41048177534bf0d9301b
Title: Corvette C2 Nero
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_64: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_68: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_72: THREE.Mesh;
    Object_73: THREE.Mesh;
    Object_78: THREE.Mesh;
    Object_75: THREE.Mesh;
    Object_76: THREE.Mesh;
    Object_82: THREE.Mesh;
    Object_84: THREE.Mesh;
    Object_80: THREE.Mesh;
    Object_86: THREE.Mesh;
    Object_88: THREE.Mesh;
    Object_90: THREE.Mesh;
    Object_92: THREE.Mesh;
    Object_94: THREE.Mesh;
    Object_95: THREE.Mesh;
    Object_103: THREE.Mesh;
    Object_101: THREE.Mesh;
    Object_105: THREE.Mesh;
    Object_98: THREE.Mesh;
    Object_99: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_112: THREE.Mesh;
    Object_110: THREE.Mesh;
    Object_120: THREE.Mesh;
    Object_118: THREE.Mesh;
    Object_122: THREE.Mesh;
    Object_115: THREE.Mesh;
    Object_116: THREE.Mesh;
    Object_124: THREE.Mesh;
    Object_129: THREE.Mesh;
    Object_127: THREE.Mesh;
    Object_137: THREE.Mesh;
    Object_135: THREE.Mesh;
    Object_139: THREE.Mesh;
    Object_132: THREE.Mesh;
    Object_133: THREE.Mesh;
    Object_141: THREE.Mesh;
    Object_146: THREE.Mesh;
    Object_144: THREE.Mesh;
    Object_153: THREE.Mesh;
    Object_151: THREE.Mesh;
    Object_155: THREE.Mesh;
    Object_148: THREE.Mesh;
    Object_149: THREE.Mesh;
    Object_157: THREE.Mesh;
    Object_162: THREE.Mesh;
    Object_160: THREE.Mesh;
  };
  materials: {
    nero: THREE.MeshStandardMaterial;
    gummi: THREE.MeshStandardMaterial;
    blink: THREE.MeshStandardMaterial;
    chrome: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    buffalo: THREE.MeshStandardMaterial;
    glas: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    titan: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    brake: THREE.MeshStandardMaterial;
    ["red.001"]: THREE.MeshStandardMaterial;
    guss: THREE.MeshStandardMaterial;
  };
};

export function Nero(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/nero/scene.gltf") as GLTFResult;
  return (
    <group position={[0, 0, 0]} {...props} dispose={null}>
      <group position={[0, -0.08, 0]} scale={[1, 1, 0.98]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.nero} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.gummi} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.blink} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.white} />
      </group>
      <group position={[0, -0.08, 0]} scale={[1, 1, 0.98]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.nero} />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.buffalo}
        />
        <mesh geometry={nodes.Object_12.geometry} material={materials.glas} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.chrome} />
      </group>
      <group position={[0, -0.08, 0]} scale={[1, 1, 0.98]}>
        <mesh geometry={nodes.Object_17.geometry} material={materials.glas} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.chrome} />
      </group>
      <group
        position={[0.37, 0.72, -1.22]}
        rotation={[-1.22, 0, 0]}
        scale={0.9}
      >
        <group
          position={[0, -0.09, -0.02]}
          rotation={[-3.14, 0, 0]}
          scale={0.35}
        >
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials.chrome}
          />
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.material}
          />
          <mesh geometry={nodes.Object_24.geometry} material={materials.nero} />
        </group>
        <mesh geometry={nodes.Object_20.geometry} material={materials.gummi} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.nero} />
      </group>
      <group position={[0.4, 0.4, -1.48]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials.gummi} />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.buffalo}
        />
      </group>
      <group position={[0, 0.41, -1.28]} rotation={[-0.1, 0, 0]}>
        <group position={[0.05, 0.07, -0.03]} rotation={[-0.16, 0, 0]}>
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials.titan}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials.nero}
            position={[0, 0.11, 0]}
          />
        </group>
        <mesh geometry={nodes.Object_34.geometry} material={materials.nero} />
      </group>
      <group
        position={[0.3, 0.78, -1.04]}
        rotation={[-1.18, 0, 0]}
        scale={0.63}
      >
        <mesh geometry={nodes.Object_42.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.glas} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.nero} />
      </group>
      <group
        position={[0.2, 0.72, -1.06]}
        rotation={[-1.21, 0, 0]}
        scale={0.41}
      >
        <mesh geometry={nodes.Object_46.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.glas} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.nero} />
      </group>
      <group
        position={[0, 0.26, -3.33]}
        rotation={[1.25, 0, Math.PI]}
        scale={0.78}
      >
        <mesh geometry={nodes.Object_54.geometry} material={materials.chrome} />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.material}
        />
        <mesh geometry={nodes.Object_56.geometry} material={materials.nero} />
      </group>
      <group position={[0, 0.63, 0.84]} rotation={[0.4, 0, 0]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials.chrome} />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.material}
        />
        <mesh geometry={nodes.Object_60.geometry} material={materials.nero} />
      </group>
      <group
        position={[0.87, 0.14, -1.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.75, 1, 0.75]}
      >
        <mesh geometry={nodes.Object_62.geometry} material={materials.chrome} />
        <mesh
          geometry={nodes.Object_64.geometry}
          material={materials.chrome}
          position={[0, -0.7, 0]}
          scale={[1.33, 1, 1.33]}
        />
        <mesh
          geometry={nodes.Object_66.geometry}
          material={materials.titan}
          position={[-0.03, 0.4, -0.01]}
        />
      </group>
      <group position={[0, -0.08, 0]} scale={[1, 1, 0.98]}>
        <mesh geometry={nodes.Object_75.geometry} material={materials.glas} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.titan} />
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials.chrome}
          position={[0.49, 0.65, 0.72]}
        />
      </group>
      <group position={[0, 0.44, 0.86]}>
        <mesh geometry={nodes.Object_80.geometry} material={materials.gummi} />
        <mesh
          geometry={nodes.Object_82.geometry}
          material={materials.material_0}
          position={[0, 0.02, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Object_84.geometry}
          material={materials.material_0}
          position={[0, 0.06, -4.25]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
      </group>
      <group position={[0, 0, -0.03]}>
        <mesh geometry={nodes.Object_94.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.chrome} />
      </group>
      <group position={[0, 0, -2.5]}>
        <group position={[0.94, 0.34, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[0, -0.09, 0]}>
            <mesh
              geometry={nodes.Object_101.geometry}
              material={materials.chrome}
            />
            <mesh
              geometry={nodes.Object_103.geometry}
              material={materials.titan}
              position={[0, -0.03, 0]}
              rotation={[0, 0, Math.PI / 2]}
            />
          </group>
          <mesh
            geometry={nodes.Object_98.geometry}
            material={materials.chrome}
          />
          <mesh
            geometry={nodes.Object_99.geometry}
            material={materials.titan}
          />
          <mesh
            geometry={nodes.Object_105.geometry}
            material={materials.chrome}
            position={[0, -0.15, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-0.3, 0.34, 0]}>
          <group position={[1, 0, 0]} scale={0.2}>
            <mesh
              geometry={nodes.Object_110.geometry}
              material={materials.guss}
            />
            <mesh
              geometry={nodes.Object_112.geometry}
              material={materials["red.001"]}
            />
          </group>
        </group>
        <mesh
          geometry={nodes.Object_107.geometry}
          material={materials.gummi}
          position={[0.92, 0.34, 0]}
        />
      </group>
      <group scale={[-1, 1, 1]}>
        <group position={[0.94, 0.34, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[0, -0.09, 0]}>
            <mesh
              geometry={nodes.Object_118.geometry}
              material={materials.chrome}
            />
            <mesh
              geometry={nodes.Object_120.geometry}
              material={materials.titan}
              position={[0, -0.03, 0]}
              rotation={[0, 0, Math.PI / 2]}
            />
          </group>
          <mesh
            geometry={nodes.Object_115.geometry}
            material={materials.chrome}
          />
          <mesh
            geometry={nodes.Object_116.geometry}
            material={materials.titan}
          />
          <mesh
            geometry={nodes.Object_122.geometry}
            material={materials.chrome}
            position={[0, -0.15, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-0.3, 0.34, 0]}>
          <group position={[1, 0, 0]} scale={0.2}>
            <mesh
              geometry={nodes.Object_127.geometry}
              material={materials.guss}
            />
            <mesh
              geometry={nodes.Object_129.geometry}
              material={materials["red.001"]}
            />
          </group>
        </group>
        <mesh
          geometry={nodes.Object_124.geometry}
          material={materials.gummi}
          position={[0.92, 0.34, 0]}
        />
      </group>
      <group position={[0, 0, -2.5]} scale={[-1, 1, 1]}>
        <group position={[0.94, 0.34, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[0, -0.09, 0]}>
            <mesh
              geometry={nodes.Object_135.geometry}
              material={materials.chrome}
            />
            <mesh
              geometry={nodes.Object_137.geometry}
              material={materials.titan}
              position={[0, -0.03, 0]}
              rotation={[0, 0, Math.PI / 2]}
            />
          </group>
          <mesh
            geometry={nodes.Object_132.geometry}
            material={materials.chrome}
          />
          <mesh
            geometry={nodes.Object_133.geometry}
            material={materials.titan}
          />
          <mesh
            geometry={nodes.Object_139.geometry}
            material={materials.chrome}
            position={[0, -0.15, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-0.3, 0.34, 0]}>
          <group position={[1, 0, 0]} scale={0.2}>
            <mesh
              geometry={nodes.Object_144.geometry}
              material={materials.guss}
            />
            <mesh
              geometry={nodes.Object_146.geometry}
              material={materials["red.001"]}
            />
          </group>
        </group>
        <mesh
          geometry={nodes.Object_141.geometry}
          material={materials.gummi}
          position={[0.92, 0.34, 0]}
        />
      </group>
      <group position={[0.94, 0.34, 0]} rotation={[0, 0, -Math.PI / 2]}>
        <group position={[0, -0.09, 0]}>
          <mesh
            geometry={nodes.Object_151.geometry}
            material={materials.chrome}
          />
          <mesh
            geometry={nodes.Object_153.geometry}
            material={materials.titan}
            position={[0, -0.03, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <mesh
          geometry={nodes.Object_148.geometry}
          material={materials.chrome}
        />
        <mesh geometry={nodes.Object_149.geometry} material={materials.titan} />
        <mesh
          geometry={nodes.Object_155.geometry}
          material={materials.chrome}
          position={[0, -0.15, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
      </group>
      <group position={[-0.3, 0.34, 0]}>
        <group position={[1, 0, 0]} scale={0.2}>
          <mesh
            geometry={nodes.Object_160.geometry}
            material={materials.guss}
          />
          <mesh
            geometry={nodes.Object_162.geometry}
            material={materials["red.001"]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.gummi}
        position={[0.4, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.buffalo}
        position={[0, -0.08, 0]}
        scale={[1, 1, 0.98]}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.buffalo}
        position={[0, -0.08, 0]}
        scale={[1, 1, 0.98]}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.chrome}
        position={[0, -0.08, 0]}
      />
      <mesh
        geometry={nodes.Object_52.geometry}
        material={materials.chrome}
        position={[0, 0.79, -3]}
        rotation={[-0.21, 0, 0]}
        scale={[0.06, 0.01, 0.06]}
      />
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials.gummi}
        position={[-0.07, 0.7, -2.21]}
      />
      <mesh
        geometry={nodes.Object_70.geometry}
        material={materials.titan}
        position={[0, -0.08, 0]}
        scale={[1, 1, 0.98]}
      />
      <mesh geometry={nodes.Object_72.geometry} material={materials.blink} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.chrome} />
      <mesh
        geometry={nodes.Object_86.geometry}
        material={materials.chrome}
        position={[0, -0.07, 0.84]}
      />
      <mesh
        geometry={nodes.Object_88.geometry}
        material={materials.gummi}
        position={[0, 0.49, -3.39]}
      />
      <mesh
        geometry={nodes.Object_90.geometry}
        material={materials.titan}
        position={[0, 1.09, -1.2]}
      />
      <mesh
        geometry={nodes.Object_92.geometry}
        material={materials.nero}
        position={[0, -0.1, -2.5]}
        scale={[1, 1, 0.98]}
      />
      <mesh
        geometry={nodes.Object_157.geometry}
        material={materials.gummi}
        position={[0.92, 0.34, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/nero/scene.gltf");
